spring:
  application:
    name: identity-service
  datasource:
    url: ${IDENTITY_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: false
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"

server:
  port: 8080
  servlet:
    context-path: /identity

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: ${VALID_DURATION}
  refreshable-duration: ${REFRESHABLE_DURATION}

app:
  config:
    url: http://localhost:8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA}