spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    format-sql: false
    open-in-view: false

server:
  port: 8087
  servlet:
    context-path: /payment

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url: http://localhost:5173/payment/success
  cancel-url: http://localhost:5173/payment/cancel
  expire-minutes: 15