spring:
  application:
    name: search-service
  ssl:
    bundle:
      pem:
        elastic:
          truststore:
            certificate: file:///home/huu-mod/elastic-http-ca.crt
  elasticsearch:
    uris: https://localhost:9200
    username: elastic
    password: Qzue*oJCvqWIbC_BQXPv
    restclient:
      ssl:
        bundle: elastic
    data:
      elasticsearch:
        repositories:
          enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8084
  servlet:
    context-path: /search

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA}
